---

#ubah dan sesuaikan semua yang diapit oleh kurung siku

- name: copy server.sh and chmod to u+x
  hosts: [192.168.56.11]
  tasks:
    - copy:
        src: server.sh
        dest: [/home/whoami/Documents/alpha-server/]
    - file:
        dest: [/home/whoami/Documents/alpha-server/server.sh]
        mode: u+x

- name: copy client.sh and chmod to u+x
  hosts: [client]
  tasks:
    - copy:
        src: client.sh
        dest: [/home/whoami/Documents/alpha-client/]
    - file:
        dest: [/home/whoami/Documents/alpha-client/client.sh]
        mode: u+x

- name: create output.log and report.txt
  hosts: [192.168.56.11]
  tasks:
    - file:
        path: [/home/whoami/Documents/alpha-server/output.log]
        state: touch
    - file:
        path: [/var/www/html/alpha-project/report.txt]
        state: touch

- name: execute server.sh
  hosts: [192.168.56.11]
  tasks:
    - command: bash [/home/whoami/Documents/alpha-server/server.sh]

- name: execute client.sh
  hosts: [client]
  tasks:
    - command: bash [/home/whoami/Documents/alpha-client/client.sh]

...
